### ISSUE TITLE
Parse error on local date (`d = 2020-01-02`) followed by any field

### ISSUE THREAD

**Issue by jschaf** [iarna/iarna-toml#23]
toml fails to parse the following block and errors with " Unexpected character, expected only whitespace or comments till end of line"

```toml
date = 2020-01-02
postType = "post"
```

### Env
node: v13.3.0
toml: `"@iarna/toml": "2.2.3"`

### Repro:
```ts
describe('toml', () => {
  it('date works', () => {
    const value = `date = 2020-01-02`;
    toml.parse(value)
  });
  
  it('date + newline + text works', () => {
    const value = `date = 2020-01-02
    
postType = "post"`;
    toml.parse(value)
  });

  it('date + text fails', () => {
    const value = `date = 2020-01-02
postType = "post"`;
    toml.parse(value)
  });

  it('date + number fails', () => {
    const value = `date = 2020-01-02
postType = 2`;
    toml.parse(value)
  });
});
```

### Stack trace:

```
TomlError: Unexpected character, expected only whitespace 
                  or comments till end of line at row 2, col 1, pos 19:
1: date = 2020-01-02
2> postType = "post"
   ^

    at TOMLParser.parseWhitespaceToEOL (@iarna/toml/lib/toml-parser.js:311:26)
    at TOMLParser.runOne (@iarna/toml/lib/parser.js:64:30)
    at TOMLParser.goto (@iarna/toml/lib/parser.js:87:17)
    at TOMLParser.recordAssignStatement (@iarna/toml/lib/toml-parser.js:337:19)
    at TOMLParser.runOne (@iarna/toml/lib/parser.js:64:30)
    at TOMLParser.returnNow (@iarna/toml/lib/parser.js:107:17)
    at TOMLParser.recordAssignValue (@iarna/toml/lib/toml-parser.js:380:19)
    at TOMLParser.runOne (@iarna/toml/lib/parser.js:64:30)
    at TOMLParser.parse (@iarna/toml/lib/parser.js:45:22)
    at Object.parseString [as parse] (@iarna/toml/parse-string.js:13:12)
```

**Comment by iarna** [comment]
Dup of #19, fixed by 5da089c
