### ISSUE TITLE
import toml using import statement in ts but failed

### ISSUE THREAD

**Issue by one0oneChen** [iarna/iarna-toml#55]
Hello, everyone. I tried to import toml using import statement in ts but failed, can someone help me
```
import toml from '@iarna/toml';
...
configdata = toml.parse(configstr)
```

```
hmr.ts:204  ReferenceError: global is not defined
    at node_modules/.pnpm/@iarna+toml@2.2.5/node_modules/@iarna/toml/lib/create-date.js (create-date.js:3:18)
    at __require (chunk-Y2F7D3TJ.js?v=4804ad59:3:50)
    at node_modules/.pnpm/@iarna+toml@2.2.5/node_modules/@iarna/toml/lib/toml-parser.js (toml-parser.js:26:20)
    at __require (chunk-Y2F7D3TJ.js?v=4804ad59:3:50)
    at node_modules/.pnpm/@iarna+toml@2.2.5/node_modules/@iarna/toml/parse-string.js (parse-string.js:4:20)
    at __require (chunk-Y2F7D3TJ.js?v=4804ad59:3:50)
    at node_modules/.pnpm/@iarna+toml@2.2.5/node_modules/@iarna/toml/parse.js (parse.js:2:18)
    at __require (chunk-Y2F7D3TJ.js?v=4804ad59:3:50)
    at node_modules/.pnpm/@iarna+toml@2.2.5/node_modules/@iarna/toml/toml.js (toml.js:2:17)
    at __require (chunk-Y2F7D3TJ.js?v=4804ad59:3:50)
warnFailedUpdate @ hmr.ts:204
fetchUpdate @ hmr.ts:237
await in fetchUpdate(异步)
(anonymous) @ client.ts:182
handleMessage @ client.ts:180
(anonymous) @ client.ts:92
显示 5 更多框架
显示简略信息
hmr.ts:206  [hmr] Failed to reload /src/components/Index.vue. This could be due to syntax errors or importing non-existent modules. (see errors above)
```

**Comment by klagrida** [comment]
how about this: import * as toml from '@iarna/toml';?

**Comment by SnowWarri0r** [comment]
@one0oneChen if you are using vite,global is not defined by default,you need to define it manually.you can see this post: https://stackoverflow.com/questions/72114775/vite-global-is-not-defined

**Comment by aspirin2d** [comment]
> how about this: import * as toml from '@iarna/toml';?

still not working.
